### PR TITLE
feat: resolve external APIs in the local build

### PR DESCRIPTION
**Pull request by jcbsfilho**
### Goal:

On the local Vulcan server, resolve external APIs with polyfill.
And in the production build, the APIs will be marked as external.

### CODE REVIEW

**Comment by jotanarciso** [comment]
I believe the polyfill should be in #env/polyfills. That is, this is an environment-adapted polyfill (env), like fetchPolyfill, and should not appear in the final build artifacts. What do you think?

**Comment by jcbsfilho** [comment]
> I believe the polyfill should be in _#env/polyfills_. That is, this is an environment-adapted polyfill (#env), like **fetchPolyfill**, and should not appear in the final build artifacts. What do you think?

I agree, let's move the external polyfills to the #env/polyfills path.
External polyfills are resolved in build, but are separated between build/polyfills and env/polyfills.

**Review by jotanarciso — APPROVED** [review]
Nice!

**Review by jotanarciso — APPROVED** [review]
Functionality works as expected. LGTM!

**Review by enicio — APPROVED** [review]

**Pull request merged**
