### PR TITLE
feat: add new gatsby preset

### PR DESCRIPTION
**Pull request by hendriksoares**
Add new preset to gastby. (mode deliver)

### CODE REVIEW

**Comment by jotanarciso** [comment]
I think you should use the mountSSG hook and not mountSPA for Gatsby. Test your project locally with Vulcan Dev to be sure.

**Comment by hendriksoares** [comment]
Narciso feedback was done and tested locally.

**Review by jotanarciso — APPROVED** [review]

**Review by maxwelbm — DISMISSED** [review]

**Review by jcbsfilho — DISMISSED** [review]

**Review by MagnunAVFAzion — CHANGES_REQUESTED** [review]
We have a typo in some parts: gastby is used instead of [gatsby](https://www.gatsbyjs.com/)

**Review by MagnunAVFAzion — APPROVED** [review]

**Review by jcbsfilho — APPROVED** [review]

**Review by jotanarciso — APPROVED** [review]

**Pull request merged**
