### PR TITLE
feat: Nextjs routing and edge runtime

### PR DESCRIPTION
**Pull request by MagnunAVFAzion**
This PR imports Nextjs build solution from [azion-framework-adapter](https://github.com/aziontech/azion-framework-adapter). This includes:
- Multiple phases routing system (vercel like);
- Edge runtime support for nextjs 12.x and 13.x (feats: static pages, ssr, ssg, edge api routes, pages format, app format - basic usage);
- Middleware support (feats: rewrite, redirect, continue to response, set request header, throw error, return response in v13.x, set response header, set response cookie);
- Next configs use (feats: rewrite before files, rewrite after files, rewrite fallback, redirects, header definition);
- i18n routing;
- Hybrid runtimes use (for v12.3.x);
- More nextjs projects examples;

More details in related PRs.

### CODE REVIEW

**Comment by tiagokrebs** [comment]
Next time, even if the feature only works after the last one, the ideal would be to break this size of change into several PR's.

**Comment by jotanarciso** [comment]
> Next time, even if the feature only works after the last one, the ideal would be to break this size of change into several smaller Pull Requests.

Yes! But they did it in the 'next' branch. Reviews were fragmented. Now all that remains is a general validation.

**Comment by MagnunAVFAzion** [comment]
This is a deploy PR. PRs for `stage` creates a pre-release version in npmjs registry. The ones for `main` creates a definitive version (available as `latest` and used by the Azion cli). We use semantic-release to automates deploy, so if we send an incomplete PR to this branchs we will generate a broked version. 
The revisions were made in a temporary `next` branch as Narciso commented. We tend to centralize the work in a temporary `next` branch when we are working on a big feature that involves several people.
Despite the context, the concern about making PRs smaller is valid!

**Review by jcbsfilho — APPROVED** [review]

**Review by jotanarciso — APPROVED** [review]

**Pull request merged**
